### ISSUE TITLE
RequestError

### ISSUE THREAD

**Issue by ernes-to** [delianides/kap-vercel#5]
Hello. I'm getting this error lately after clicking "Convert" and uploading to Vercel. I've generated a new token on Vercel, but the issue persists. Using the latest stable version of Kap.

**macOS version:**    Big Sur (11)
**Kap version:**      3.4.1

```
RequestError

RequestError: certificate has expired
    at ClientRequest.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/got/source/request-as-event-emitter.js:178:14)
    at ClientRequest.origin.emit (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

**Comment by delianides** [comment]
Resolved with 0.4.4
